#########################################################
#                                                       #
#                Akiki Giftcodes - Config               #
#                                                       #
#########################################################

check-update: true # false de tat

messages:
  invalid-code: "Mã quà tặng bạn đã nhập không hợp lệ."
  code-expired: "Mã quà tặng bạn nhập đã hết hạn."
  max-uses-reached: "Mã quà tặng bạn nhập đã đạt số lần sử dụng tối đa."
  code-disabled: "Mã quà tặng bạn nhập hiện đã bị vô hiệu hóa."
  code-redeemed: "Bạn đã đổi mã quà tặng thành công!"
  code-already-redeemed: "Bạn đã đổi mã này rồi."
