name: AsakaGiftcodes
version: '1.1-R1'
main: me.blubriu.asakaGiftcodes.AsakaGiftcodes
api-version: '1.20'
authors: [ BlubRiu ]
description: AsakaGiftcode Plugin MC
website: https://blueberry.is-a.dev

commands:
  giftcode:
    usage: /<command>
    permission: giftcode.admin
    aliases: [gc]
  code:
    usage: /<command>

permissions:
  giftcode.admin:
    default: op
  giftcode.player:
    default: true